name: Testing
on:
  push:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Build
        run: go build -v ./...
      - name: Test
        run: |
          go test ./... -v -coverpkg=./... -coverprofile=coverage.out
          pwd
          ls -al
      - uses: actions/upload-artifact@master
        with:
          name: artifact
          path: ${{ github.workspace }}/
          retention-days: 5
  sonarcloud:
    needs: unit-test
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: artifact
          path: ${{ github.workspace }}/
      - name: check contents
        run: |
          pwd
          ls -al
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Dynamic-Analysis-OWASP-ZAP: #TODO: Move to a separate repo to scan remote URLs
    permissions: write-all
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: artifact
          path: ${{ github.workspace }}/

#      - name: run docker image
#        run: docker run -d -p 8080:8080 $(docker build -q -f Dockerfile .)

      - name: OWASP ZAP
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          # Target URL
          target: "http://ev-charger-load-balancer-1794260920.ap-southeast-1.elb.amazonaws.com/api/v1"
          fail_action: false
          allow_issue_writing: true
          issue_title: Security Tests
